@BLOGLISTSERVICE = http://localhost:3001

POST {{BLOGLISTSERVICE}}/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJzZWNvbmRAVXNlci5jb20iLCJpYXQiOjE3MjY5MzMwNDIsImV4cCI6MTcyNjkzMzk0Mn0.oNHe6KHTtqGCEs74eUkLKf7OBmFjD_V8in-436n6iL0

{"author":"Matti Luukainen","url":"https://helsinki.academia.edu/MattiLuukkainen","title":"Fullstack","likes":0,"year":2000}
###