@BLOGLISTSERVICE = http://localhost:3001

POST {{BLOGLISTSERVICE}}/api/users
Content-Type: application/json

{"username":"defaul@User.com","name":"Display Name","password":"aPassword"}
###
POST {{BLOGLISTSERVICE}}/api/users
Content-Type: application/json

{"username":"second@User.com","name":"DisplayName2","password":"aaais"}
###
POST {{BLOGLISTSERVICE}}/api/users
Content-Type: application/json

{"username":"ajsi@Gust.com","name":"AJSI","password":"ttttes"}